language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "12"

services:
  - mongodb

env:
  - DATABASE_URI=mongodb://admin:admin@127.0.0.1/mydb_test

os:
  - linux
  - windows

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"admin",pwd:"admin",roles:["readWrite"]});'

script:
  - npm run lint && npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: always
