name: Test Action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Test ENV
      run: |
        docker run -d -p 27017:27017 mongo
    - name: npm install and test
      run: |
        npm install
        npm run test
